'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "../../components/Sidebar";
import { usePathname, useSearchParams} from 'next/navigation'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {

  const pathname = usePathname();
  const searchParams = useSearchParams();
  return (

    pathname==="/login" || pathname==="/login/signin"?
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div>
        <main className="">
          <div className="bg-gray-800 min-h-screen flex flex-col justify-center">
          {children}
          </div>
        </main>
        
      </div>  
      </body>
    </html>
    :
    
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div>
         <div className="flex min-h-screen">
        <Sidebar/>
        <main className="sm:w-2/3 xl:w-4/5 sm:min-h-screen p-5">
          {children}
        </main>
        </div>
      </div>  
      </body>
    </html>
  );
}
